<?php

use think\facade\Route;
/*
Route::rule('one','free/one');
Route::rule('fsubmit','free/submit');
Route::rule('fsigncheck','free/signcheck');
Route::rule('preview','free/preview');
Route::rule('signfreet','free/signaturet');
Route::rule('signfree','free/signpage');
Route::rule('freesave','free/save'); 
Route::rule('free','free/index'); */

Route::rule('one','key/one');
Route::rule('fsubmit','key/submit');
Route::rule('fsigncheck','key/signcheck');
Route::rule('preview','key/preview');
Route::rule('signfreet','key/signaturet');
Route::rule('signfree','key/signpage');
Route::rule('freesave','key/save'); 
Route::rule('key','key/index');

Route::rule('rsignature','rentalincome/signaturet'); 
Route::rule('rsave','rentalincome/save');
Route::rule('rsubmit','rentalincome/submit');
Route::rule('r_topdf','rentalincome/topdf'); 
Route::rule('rentalincome','rentalincome/index');

Route::rule('all_signpage','all/signpage');
Route::rule('allscheck','all/signcheck');
Route::rule('allsignature','all/signaturet'); 
Route::rule('allsave','all/save');
Route::rule('allsubmit','all/submit');
Route::rule('all_topdf','all/topdf'); 
Route::rule('all','all/index');

Route::rule('dscheck','dependent/signcheck'); 
Route::rule('dsignature','dependent/signaturet'); 
Route::rule('de_signpage','dependent/signpage');
Route::rule('depsave','dependent/depsave');
Route::rule('depsubmit','dependent/depsubmit');
Route::rule('dependent_topdf','dependent/dependent_topdf'); 
Route::rule('dependent','dependent/dependent'); 

Route::rule('isave','insolvency/isave');
Route::rule('isubmit','insolvency/isubmit');
Route::rule('insolvency_topdf','insolvency/insolvency_topdf'); 
Route::rule('insolvency','insolvency/insolvency'); 

Route::rule('dsave','deductions/dsave');
Route::rule('desubmit','deductions/desubmit');
Route::rule('deductions_topdf','deductions/deductions_topdf'); 
Route::rule('deductions','deductions/deductions'); 


Route::rule('f_remove','financial/file_remove'); 
Route::rule('f_upload','financial/file_upload'); 
Route::rule('scheck','financial/signcheck'); 
Route::rule('rentaldownload','financial/downloadfile'); 
Route::rule('cm_ajax_remove','financial/ajax_remove');
Route::rule('cm_ajax_upload','financial/ajax_upload'); 
Route::rule('upload','financial/upload'); 
Route::rule('signpage2','financial/signpage2'); 
Route::rule('signpage1','financial/signpage'); 
Route::rule('signatures','financial/signatures'); 
Route::rule('signaturet','financial/signaturet'); 
Route::rule('cm_topdf','financial/cm_topdf'); 
Route::rule('cmsave','financial/cmsave');
Route::rule('cmsubmit','financial/submit'); 
Route::rule('financial','financial/financial'); 
Route::rule('financial_upload','financial/financial_upload'); 

//Route::rule('login','index/login');
Route::rule('signcheck','Profitloss/signcheck'); 
Route::rule('plsubmit','Profitloss/submit'); 
Route::rule('iframe','Profitloss/iframe'); 
Route::rule('getcurField','Profitloss/getcurField'); 
Route::rule('signpage','Profitloss/signpage'); 
Route::rule('signature','Profitloss/signature'); 
Route::rule('pl_save','Profitloss/profitsave'); 
Route::rule('pl_topdf','Profitloss/topdf'); 
Route::rule('files','Profitloss/files'); 
//
Route::rule('preclient','Eapi/preclient');
Route::rule('gettype','Eapi/gettype');
Route::rule('acapi','Eapi/acapi');
Route::rule('aclient','Eapi/addclient'); 

Route::rule('sendbatch','Eapi/sendbatch'); 
Route::rule('singleEmailSend','Eapi/singleEmailSend'); 
Route::rule('emailSend','Eapi/emailSend'); 
Route::rule('ajax_getFilename','Api/ajax_getFilename'); 
Route::rule('reSubmit','Api/reSubmit'); 
Route::rule('unlock','Api/unlock'); 
Route::rule('removeChecklist','Api/removeChecklist'); 
Route::rule('getChecklistDetail','Api/getChecklistDetail'); 
Route::rule('getNewDetail','Api/getNewDetail'); 
Route::rule('addCheck','Api/addCheck');  //添加checklist
Route::rule('getCheckDetail','Api/getCheckDetail'); 
Route::rule('addCheckFile','Api/addCheckFile'); 
Route::rule('editCheck','Api/editCheck'); 
Route::rule('removeCheck','Api/removeCheck'); 

Route::rule('topdf_wkhtmltopdf','Api/topdf_wkhtmltopdf'); 
Route::rule('topdf_mpdf','Api/topdf_mpdf'); 
Route::rule('topdf','Api/topdf'); 
Route::rule('downloadfile','Api/downloadfile'); 
Route::rule('downloadzip','Api/downloadzip'); 
Route::rule('finishpage','Api/finishpage'); 
Route::rule('getpagenext','Api/getpagenext'); //保存每个字段
Route::rule('pagesave_form','Api/pagesave_form'); //保存每个字段
Route::rule('ajax_remove','Api/ajax_remove'); //保存每个字段
Route::rule('ajax_upload','Api/ajax_upload'); //保存每个字段
Route::rule('pagesave','Api/pagesave'); //保存每个字段
Route::rule('submission','Api/submission'); //删除client
Route::rule('folders','Api/folders'); //删除client
Route::rule('delClient','User/delClient'); //删除client
Route::rule('center','User/center');
Route::rule('addclient','User/addclient'); //增加client界面1
/********************{index控制器}********************/
Route::rule('fbpage','Index/fbpage');
Route::rule('cancelcallback','Index/cancelcallback');
Route::rule('actback','Index/actback');
Route::rule('adcallback','Index/adcallback');
Route::rule('fb_return2','Api/fb_return');
Route::rule('callback','Index/callback');
Route::rule('fb_return','Index/fbreturn');
Route::rule('/','Index/index');
//Route::rule('get_dizhi','Index/get_location');
//Route::rule('fujin','Index/nearby');
//Route::rule('get_fujin','Index/get_nearby');
Route::rule('get_diqu','Index/get_region');
Route::rule('index_request_goods','Index/ajax_index');
/********************{shop控制器}********************/
//Route::rule('jf_store','Shop/index');
//Route::rule('store_request_goods','Shop/ajax_index');
//Route::rule('jifen_goods_xq/:goods_id','Shop/jifen_goods_info');
//Route::rule('jifen_goods_gm/:goods_id','Shop/jifen_goods_buy');
/********************{shouyi控制器}********************/
//Route::rule('shouyi','Shouyi/index');
//Route::rule('quyu','Shouyi/qy_daili');
//Route::rule('quyu_points','Shouyi/dl_points');
//Route::rule('ajax_quyu_points','Shouyi/ajax_dl_points');
//Route::rule('hy_points','Shouyi/hy_points');
//Route::rule('ajax_hy_points','Shouyi/ajax_hy_points');
//Route::rule('ajax_fahuo_order','Shouyi/ajax_send_order');
//Route::rule('fahuo/:order_id','Shouyi/order_send');
//Route::rule('td_dingdan','Shouyi/td_order');
//Route::rule('ajax_td_dingdan','Shouyi/ajax_td_order');
/********************{circle控制器}********************/
//Route::rule('quanzi','Circle/index');
//Route::rule('ajax_quanzi','Circle/ajax_get_circle');
//Route::rule('quanzi_xq/:id','Circle/circle_detail');
//Route::rule('quanzi_zan','Circle/circle_zan');
//Route::rule('quanzi_sc','Circle/circle_del');
//Route::rule('quanzi_pl','Circle/circle_comment');
//Route::rule('ajax_quanzi_pl','Circle/ajax_get_circle_comment');
//Route::rule('user_qz/:user_id','Circle/user_circle');
//Route::rule('fabu','Circle/issue');
/********************{yunpian控制器}********************/
Route::rule('send_code','Yunpian/index');
/********************{user控制器}********************/
Route::rule('my','User/index');
Route::rule('my_info','User/user_info');
Route::rule('my_xinxi','User/info');
Route::rule('dengji','User/level');
//Route::rule('my_nicheng','User/nickname');
Route::rule('my_xm','User/realname');
//Route::rule('my_dl','User/team_index');
Route::rule('my_td/[:user_id]','User/team');
Route::rule('ajax_my_td','User/ajax_team');
Route::rule('my_zijin/[:type]','User/points');
Route::rule('ajax_zijin','User/ajax_points');
//Route::rule('xiaoxi','User/message');
//Route::rule('ajax_xiaoxi','User/ajax_message');
//Route::rule('xiaoxi_xq/:id','User/message_detail');
Route::rule('my_yue','User/lingqian');
//Route::rule('my_jf','User/jifen');
//Route::rule('my_jl/:type','User/jl_log');
//Route::rule('ajax_my_jl','User/ajax_jl_log');
Route::rule('tixian/[:type]','User/withdrawals');
Route::rule('tx_list','User/withdrawals_list');
Route::rule('ajax_tx_list','User/ajax_with');
Route::rule('user_cz','User/recharge');
Route::rule('user_cz_list','User/recharge_list');
Route::rule('ajax_cz_list','User/ajax_recharge_list');
//Route::rule('zhuanzeng','User/given');
//Route::rule('zhuanzeng_list','User/given_list');
//Route::rule('ajax_zhuanzeng_list','User/ajax_given_list');
Route::rule('my_mima','User/password');
Route::rule('zf_mima','User/paypwd');
Route::rule('erweima','User/qrcode');
Route::rule('my_shoucang','User/collect_list');
Route::rule('ajax_get_shoucang','User/ajax_collect');
Route::rule('my_shoucang_del','User/collect_del');
Route::rule('my_visit','User/visit_log');
Route::rule('ajax_get_visit','User/ajax_visit');
Route::rule('my_visit_del','User/visit_del');
Route::rule('my_address','User/address_list');
Route::rule('my_address_edit','User/add_edit_address');
Route::rule('my_address_save','User/address_save');
Route::rule('my_address_set','User/set_default');
Route::rule('my_address_del','User/del_address');
Route::rule('login','User/login');
//Route::rule('denglu','User/login');
Route::rule('do_login','User/do_login');
//Route::rule('do_denglu','User/do_login');
Route::rule('do_register','User/reg');
Route::rule('do_forget','User/forget_pwd');
Route::rule('logout','User/logout');
Route::rule('imageUp','User/upload_pic');
Route::rule('save_head_pic','User/head_pic_upload');
//Route::rule('qiandao','User/sign');
Route::rule('do_qiandao','User/do_sign');
//Route::rule('ajax_get_qiandao','User/ajax_get_sign');
/********************{goods控制器}********************/
Route::rule('product','Goods/goods_list');
Route::rule('product_xq/[:id]','Goods/goods_info');
Route::rule('product_sc','Goods/collect_goods');
Route::rule('ajax_get_product','Goods/ajax_goods');
Route::rule('fenlei','Goods/category_list');
//Route::rule('ajax_fenlei','Goods/ajax_cate');
Route::rule('ajax_get_cate_product','Goods/ajax_cate_goods');
/********************{cart控制器}********************/
Route::rule('gouwuche','Cart/index');
Route::rule('gouwuche_del','Cart/delete');
Route::rule('gouwuche_add','Cart/cart_add');
Route::rule('do_gouwuche','Cart/do_cart');
Route::rule('gouwuche_tj','Cart/cart');
/********************{order订单管理控制器}********************/
Route::rule('indent','Order/order_list');
Route::rule('td_indent/:user_id','Order/td_order_list');
Route::rule('ajax_td_indent','Order/ajax_td_order_list');
Route::rule('ajax_get_indent','Order/ajax_order');
Route::rule('order_qx','Order/cancel_order');
Route::rule('order_qr','Order/order_confirm');
Route::rule('order_xq/:order_id','Order/order_detail');
Route::rule('order_wuliu/:order_id','Order/logistics');
/********************{content控制器}********************/
Route::rule('gonggao','Content/essay_list');
Route::rule('ajax_gonggao','Content/ajax_essay_list');
Route::rule('gonggao_xq/:artid','Content/essay_detail');
Route::rule('wenzhang','Content/ajax_article_list');
Route::rule('wenzhang_xq/:artid','Content/article_detail');
Route::rule('xieyi_xq/:artid','Content/protocol_detail');
Route::rule('shipins','Content/video_list');
Route::rule('ajax_shipins','Content/ajax_video_list');
/********************{payment控制器}********************/
Route::rule('zhifu/:pay_code/[:order_sn]','Payment/get_code');
Route::rule('zhifu_return','Payment/return_url');
Route::rule('zhifu_notify/[:pay_code]','Payment/notify_url');
Route::rule('zhifu_weixin','Payment/weixin_return');